data = {b'10.1038/s42003-020-0859-7': {"pubdate": 2021.25,
                                       "title": ["The gut microbiome but not the resistome is associated with urogenital schistosomiasis in preschool-aged children"],
                                       "caller": "Brinch",
                                       "author": ["Osakunor, Derick", "Munk, Patrick", "Mduluza, Takafira", "Petersen, Thomas N.", "Brinch, Christian", "Ivens, Alasdair", "Chimponda, Theresa", "Amanfo, Seth A.", "Murray, Janice", "Woolhouse, Mark E. J.", "Aarestrup, Frank M.", "Mutapi, Francisca"],
                                       "citations": 10,
                                       "citations_by_month": [2021.5, 2021.5, 2021.5, 2021.83, 2022.0, 2022.5, 2022.33, 2022.42, 2022.5, 2022.58],
                                       "selfcitations": 0,
                                       "pub": "Commun. Biol.",
                                       "volume": "3",
                                       "page": [155],
                                       "doi": "10.1038/s42003-020-0859-7"},
        b'10.1128/mSystems.00841-20': {"pubdate": 2020.75,
                                       "title": ["Long-Term Temporal Stability of the Resistome in Sewage from Copenhagen"],
                                       "caller": "Brinch",
                                       "author": ["Brinch, Christian", "Leekitcharoenphon, Pimlapas", "Duarte, Ana S. R.", "Svendsen, Christina A.", "Jensen, Jacob D.", "Aarestrup, Frank M."],
                                       "citations": 4,
                                       "citations_by_month": [2021.42, 2022.25, 2022.92, 2023.25],
                                       "selfcitations": 0,
                                       "pub": "mSystems",
                                       "volume": "5",
                                       "page": ["e00841-20"],
                                       "doi": "10.1128/mSystems.00841-20",
                                       },
        b'10.1128/msystems.00105-22': {"pubdate": 2022.25,
                                       "title": ["Global Distribution of mcr Gene Variants in 214K Metagenomic Samples"],
                                       "caller": "Brinch",
                                       "author": ["Martiny, Hannah-Marie", "Munk, Patrick", "Brinch, Christian", "Szarvas, Judit", "Aarestrup, Frank M.", "Petersen, Thomas N."],
                                       "citations": 9,
                                       "citations_by_month": [2022.83, 2022.75, 2022.75, 2022.67, 2022.5, 2022.58, 2023.25, 2023.25, 2023.5],
                                       "selfcitations": 0,
                                       "pub": "mSystems",
                                       "volume": "7",
                                       "page": ["e00105-22"],
                                       "doi": "10.1128/msystems.00105-22"
                                       },
        b'10.1371/journal.pbio.3001792': {"pubdate": 2022.67,
                                          "title": ["A curated data resource of 214K metagenomes for characterization of the global antimicrobial resistome"],
                                          "caller": "Brinch",
                                          "author": ["Martiny, Hannah-Marie", "Bollenbach, Tobias", "Munk, Patrick", "Brinch, Christian", "Aarestrup, Frank M.", "Petersen, Thomas N."],
                                          "citations": 2,
                                          "citations_by_month": [2022.83, 2023.17],
                                          "selfcitations": 0,
                                          "pub": "PLoS Biol.",
                                          "volume": "",
                                          "page": [0],
                                          "doi": "10.1371/journal.pbio.3001792"
                                          },
        b'10.1186/s40168-022-01357-1': {"pubdate": 2022.67,
                                        "title": ["A global phylogenomic and metabolic reconstruction of the large intestine bacterial community of domesticated cattle"],
                                        "caller": "Brinch",
                                        "author": ["Teseo, S.", "Otani, Saria", "Brinch, Christian", "Leroy, S.", "Ruiz, P.", "Desvaux, M.", "Forano, E.",  "Aarestrup, F. M.",  "Sapountzis, P."],
                                        "citations": 2,
                                        "citations_by_month": [2023.17, 2023.17],
                                        "selfcitations": 0,
                                        "pub": "Microbiome",
                                        "volume": "10",
                                        "page": [155],
                                        "doi": "10.1186/s40168-022-01357-1"
                                        },
        b'10.1038/s41467-022-34312-7': {"pubdate": 2022.92,
                                        "title": ["Genomic analysis of sewage from 101 countries reveals global landscape of antimicrobial resistance"],
                                        "caller": "Brinch",
                                        "author": ["Munk, P.", "Brinch, C.", "Møller, F. D.", "Petersen, T. N.", "Hendriksen, R. S.", "Seyfarth, A. M.", "Kjeldgaard, J. S.", "Svendsen, C. A.", "Bunnik, B. v.", "Berglund, F.", "Global Sewage Surveillance Consortium", "Larsson, D. G. J.", "Koopmans, M.", "Woolhouse, M.",  "Aarestrup, F. M."],
                                        "citations": 8,
                                        "citations_by_month": [2022.92, 2023., 2023.17, 2023.17, 2023.17, 2023.25, 2023.33, 2023.66],
                                        "selfcitations": 0,
                                        "pub": "Nat Commun.",
                                        "volume": "13",
                                        "page": [7251],
                                        "doi": "10.1038/s41467-022-34312-7"
                                        },
        b'10.3389/fevo.2023.981377': {"pubdate": 2023.16,
                                      "title": ["Interplay between strain fitness and transmission frequency determines prevalence of antimicrobial resistance"],
                                      "caller": "Brinch",
                                      "author": ["Bogri, A.", "Otani, S.", "Aarestrup, F. M.", "Brinch, C."],
                                      "citations": 0,
                                      "citations_by_month": [],
                                      "selfcitations": 0,
                                      "pub": "Front. Ecol. Evol.",
                                      "volume": "11",
                                      "page": [0],
                                      "doi": "10.3389/fevo.2023.981377"
                                      },
        }
